#! /usr/bin/env bash
PATH="/usr/local/opt/curl/bin:$PATH"
LW_CA_CERT=$HOME/incubator/ssl/ops-ca.crt
user=eml
pwkey="LincWare LDAP"
pw=$(-pw "$pwkey")
[ -z "$pw" ] && {
  echo "Could not retrieve password" >&2
  exit 1
}
auth=$(printf "%s:%s" "$user" "$pw" | openssl enc -a -A)
auth_hdr=$(printf "Authorization: Basic %s" $auth)
ra_agent_id_hdr="X-Ra-Agent-Id: remoteadmin.private/127.0.0.1"
#ra_agent_id_hdr="X-Ra-Agent-Id: xerus1.lincware.com/10.9.0.80"

#url=https://remoteadmin.private:3001/ra-runtime-config
url=https://remoteadmin.private:3333/ra-runtime-config

ra-runtime-config() {
  #url=https://remoteadmin.private:3001/ra-runtime-config
  #code64=$(printf "JSON.stringify(self.config.RA_USER_AUTHORIZED_HOSTS,null,1)" | openssl enc -a -A)
  #code64=$(printf "self.config.RA_USER_AUTHORIZED_HOSTS['abdel.mawla']='issworld.com|americaninhomecare.com|discoveryliving|aomofny.com|ltc.admitplus.work|aplusdev.tsgrinc.com'" | openssl enc -a -A)
  #code64=$(printf "self.config.RA_USER_AUTHORIZED_HOSTS['paul.ratilla']='ltc.admitplus.work'" | openssl enc -a -A)
  #code64=$(printf "self.config.RA_CHECK_FOR_REBOOTS_NOTIFY='support_cc@lincware.com'" | openssl enc -a -A)
  #code64=$(printf "self.config.RA_USER_AUTHORIZED_HOSTS['mohammad.shahid'].push('admit.work')" | openssl enc -a -A)
  #code64=$(printf "var a=['fundltc','altercare','tsgrinc'];self.config.RA_USER_AUTHORIZED_HOSTS['data.divincenzo']=a;" | openssl enc -a -A)
  #code64=$(printf "self.config.RA_USER_AUTHORIZED_HOSTS['abdel.mawla'].push('lincwareweb01test.altercareonline.com')" | openssl enc -a -A)
  #code64=$(printf "self.config.RA_USER_AUTHORIZED_HOSTS['rado'].push('gp1lincdoc-dev.group1auto.com')" | openssl enc -a -A)
  #code64=$(printf "self.config.RA_USER_AUTHORIZED_HOSTS['abdel.mawla'].push('colina.com')" | openssl enc -a -A)
  #code64=$(printf "self.config.RA_USER_AUTHORIZED_HOSTS['abdel.mawla']=['.']" | openssl enc -a -A)
  #code64=$(printf "var a=self.config.RA_USER_AUTHORIZED_HOSTS['abdel.mawla'];a.push('bangorpayroll.com');JSON.stringify(a)" | openssl enc -a -A)
  #code64=$(printf "self.config.RA_USER_AUTHORIZED_HOSTS['faizan.shabbir'].push('issworld.com')" | openssl enc -a -A)
  #code64=$(printf "self.config.RA_USER_AUTHORIZED_HOSTS['jhowell.corotan'].push('pratt.edu')" | openssl enc -a -A)
  #code64=$(printf "self.config.RA_USER_AUTHORIZED_HOSTS['mayowa.ijigade']=['ltc.admitplus.work']" | openssl enc -a -A)
  #code64=$(printf "self.config.RA_USER_AUTHORIZED_HOSTS['rado'].push('ltc.admitplus.work')" | openssl enc -a -A)
  #code64=$(printf "JSON.stringify(self.config.RA_USER_AUTHORIZED_HOSTS['abdel.mawla'])" | openssl enc -a -A)
  #code64=$(printf "self.config.RA_USER_AUTHORIZED_HOSTS['aarti.sharma'].push('lincdoc-test.aomofny.com')" | openssl enc -a -A)
  #code64=$(printf "self.config.RA_USER_AUTHORIZED_HOSTS['zaheer.amed'].push('lincdoc-dev.aomofny.com')" | openssl enc -a -A)
  #code64=$(printf "self.config.RA_USER_AUTHORIZED_HOSTS['aarti.sharma'].push('lincdoc-prod-20220224.aomofny.com')" | openssl enc -a -A)
  #code64=$(printf "self.config.RA_USER_AUTHORIZED_HOSTS['aarti.sharma'].push('lincdoc-test.aomofny.com')" | openssl enc -a -A)
  #code64=$(printf "console.log('ans:',self.config.RA_SYSTEM_SECRETS.systems['ldap.lincware.com'])" | openssl enc -a -A)
  #code64=$(printf "self.secrets.getSecretsForHost('ldap.lincware.com')" | openssl enc -a -A)
  #code64=$(printf "self.config.RA_USER_AUTHORIZED_HOSTS['sreeraj.punnoli']=['ltc.admitplus.work','devops','fundltc-test','training.admit.work']" | openssl enc -a -A)
  code64=$(printf "self.config.RA_USER_AUTHORIZED_HOSTS['sreeraj.punnoli'].push('pruitthealth.admit.work')" | openssl enc -a -A)

  code64b=$(printf "
    var a=[];
    for (var [sshPort,agent] of RaAgent.getAgents()) {
      //a.push(agent.getUniqueId());
      a.push(agent);
    }
    a
" | openssl enc -a -A)

  curl -S -v -f --cacert $LW_CA_CERT -X POST -H "$ra_agent_id_hdr" -H "Content-Type: application/json" -H "$auth_hdr" -d "{\"eval\":\"$code64\"}" $url
  #curl -v -X POST -H "$ra_agent_id_hdr" -H "Content-Type: application/json" -H "$auth_hdr" -d "{\"config\":{\"RA_USER_AUTHORIZED_HOSTS\":{\"eml\":\"my value\"}}}" $url
}

ra-runtime-config;exit

ra-root-cmd() {
  local url=https://remoteadmin.private:3001/ra-root-cmd
  local ra_agent_id_hdr="X-Ra-Agent-Id: xerus1.lincware.com/10.9.0.80"
  #local cmdArrayString='["pwd"]'
  local cmdArrayString='["cat","\\$RA_TOMCAT_SERVER_XML"]'
  echo "$cmdArrayString" | curl -S -v -f --cacert $LW_CA_CERT -X POST -H "$ra_agent_id_hdr" -H "Content-Type: application/json" -H "$auth_hdr" -d @- $url
}

ra-root-cmd;exit

attempt=1
n=5
set -e

while true; do
  for((i=1;i<=$n;i++)); do
    ra-runtime-config &
  done
  for((i=1;i<=$n;i++)); do
    wait %$i
  done
done
echo "DONE"


ra-set-log-threshold() {
  url=https://remoteadmin.private:3001/$FUNCNAME
  #logId=RaCronJobGatherAgentStatuses
  logId=RaCron
  threshold=trace
  curl -v -f -X POST -H "$ra_agent_id_hdr" -H "Content-Type: application/json" -H "$auth_hdr" -d "{\"logId\":\"$logId\",\"threshold\":\"$threshold\"}" $url
}

#ra-set-log-threshold
