#!/usr/bin/env bash
set -e
set -o pipefail
port=2543
siriusxmurl=https://raw.githubusercontent.com/andrew0/SiriusXM/master/sxm.py
siriusxmuser=eric@lincware.com

list_channels() {
  python3 - $siriusxmuser $(pw siriusxm:$siriusxmuser) --list < <(curl --silent $siriusxmurl)
}

if channels=$(list_channels) && [ $? -ne 1 ] && [ $? -ne 0 ]; then
  exit $?
fi

channel=$(pick_something "Pick a channel:" "$channels" | cut -d' ' -f1)

set +e

# start m3u8 server
python3 - $siriusxmuser $(pw siriusxm:$siriusxmuser) -p $port < <(curl --silent $siriusxmurl) &
python_pid=$!

trap '{
  echo "killing python back end: $python_pid"
  kill $python_pid
}' EXIT INT QUIT

sleep=5
echo "Starting channel \"$channel\" in $sleep seconds ..."
sleep $sleep
url=http://localhost:$port/$channel.m3u8
os=$(uname)

case $os in
  Darwin)
    /Applications/VLC.app/Contents/MacOS/VLC $url
    ;;
  Linux|OpenBSD)
    vlc $url
    ;;
  *)
    echo "Error: need support for os=$os"
    exit 1
    ;;
esac
