#! /bin/bash
# create hostonly interface after a reboot
interface=vboxnet0
ifconfig | grep -q $interface && echo "$interface already configured" || {
  #VBoxManage hostonlyif create
  VBoxManage hostonlyif ipconfig $interface --ip 192.168.5.1 --netmask 255.255.255.0
}
