#! /usr/bin/env bash

export SCR_PORT=4553
export SCR_ENV=dev
shell_init_args=(-s 1)

usage() {
  echo "Usage: $0 [-h][-Ct][-p port][-g \"test_group1 ...\"][-G]
Options:
-h       this help
-C       clear the cache
-p port  port number of the Server.js process
-t       test mode (for developers only)
-g       specify test groups (limit tests to only these groups)
-G       show all available test groups
"
}

while builtin getopts "hCp:tg:G" opt; do
  case $opt in
    (h)
      usage
      exit
      ;;
    (p)
      SCR_PORT=$OPTARG
      ;;
    (t)
      shell_init_args+=(-t)
      SCR_ENV=test
      ;;
    (C)
      shell_init_args+=(-C)
      ;;
    (g)
      shell_init_args+=(-g "$OPTARG")
      ;;
    (G)
      shell_init_args+=(-G)
      ;;
  esac
done

url="http://127.0.0.1:$SCR_PORT/scr-get-bash-functions"
eval "$(curl -S -f -s --compressed $url)"
-shell-init "${shell_init_args[@]}"
