#! /usr/bin/env bash

export SCR_PORT=4553
TEST_MODE=''

while builtin getopts "p:t" opt; do
  case $opt in
    (p)
      SCR_PORT=$OPTARG
      ;;
    (t)
      TEST_MODE="-t"
      ;;
  esac
done

url="http://127.0.0.1:$SCR_PORT/scr-get-bash-functions?start=1"
eval "$(curl -S -f -s --compressed $url)"
#eval "$(-shell-init -v -s 1 $TEST_MODE)"
