#! /usr/bin/env bash

export SCR_PORT=4553
export SCR_ENV=dev
export SCR_HOME=$(node -r fs -r path -e "console.log(fs.realpathSync(path.join('$0','..')))")
shell_init_args=(-s 1)

usage() {
  echo "Usage: $0 [-h][-C][-p port]
Options:
-h       this help
-C       clear the cache
-p port  port number of the Server.js process
"
}

while builtin getopts "hCp:" opt; do
  case $opt in
    (h)
      usage
      exit
      ;;
    (p)
      SCR_PORT=$OPTARG
      ;;
    (C)
      shell_init_args+=(-C)
      ;;
  esac
done

url="http://127.0.0.1:$SCR_PORT/scr-get-bash-functions"
eval -- "$(curl -S -f -s --compressed $url)"
-shell-init "${shell_init_args[@]}"
