#! /usr/bin/env bash

export SCR_PORT=4553
export SCR_ENV=${SCR_ENV:=dev}
export SCR_PROFILE=$USER
eval $(node -r fs -r path -e 'const h=path.join(fs.realpathSync(process.argv[1]),".."); const p=require(path.join(h,"package.json")); console.log(`export SCR_HOME="${h}" SCR_VERSION=${p.version}`);' -- $0)
client_server_mode=0
shell_init_args=()

usage() {
  echo "Usage: $0 [-h][-C][-p port][-s][-P profile]
Options:
-h           this help
-C           clear the cache
-p port      port number of the Server.js process, default is $SCR_PORT
-s           client/server mode: start a server process inside a new gnu screen session
-P profile   select a custom scrash profile, defaults to \$USER
"
}

while builtin getopts "hCp:P:s" opt; do
  case $opt in
    (h)
      usage
      exit
      ;;
    (p)
      SCR_PORT=$OPTARG
      ;;
    (P)
      SCR_PROFILE=$OPTARG
      ;;
    (C)
      shell_init_args+=(-C)
      ;;
    (s)
      client_server_mode=1
      ;;
  esac
done

if [ $client_server_mode = 1 ]; then
  export SCR_PASSWORD_FILE="$SCR_HOME/profile/$SCR_PROFILE/passwords.gpg"
  export SCR_TMPDIR=/tmp/scr-$SCR_ENV-$SCR_PORT
  source "$SCR_HOME/src/bash/bash-functions"
  for rcfile in "$SCR_HOME"/profile/$SCR_PROFILE/{screenrc,bashrc,vimrc}; do
    rcfile_base=$(basename $rcfile)
    if [ -f $rcfile ]; then
      printf -v funcdef -- "-%s() { cat %s; }" $rcfile_base $rcfile
    else
      printf -v funcdef -- "-%s() { :; }" $rcfile_base
    fi
    eval -- "$funcdef"
  done
  eval -- "$(-bashrc)"
  -vim-plugin-clipboard() {
    cat "$SCR_HOME/src/vim/clipboard.vim"
  }
  -scr-server() {
    npm start --prefix="$SCR_HOME" -- -p $SCR_PORT
    echo "$FUNCNAME: server has stopped" >&2
    exec bash
  }
  shell_init_args+=(-s $(-ssh-serialize-cmd screen bash -c -- -scr-server))
else
  shell_init_args+=(-s 1)
  url="http://127.0.0.1:$SCR_PORT/scr-get-bash-functions"
  eval -- "$(curl -S -f -s --compressed $url)"
fi
-shell-init "${shell_init_args[@]}"
