#! /usr/bin/env bash

export SCR_PORT=$((50000+$RANDOM % 10000))

for opt in "$@"; do
  case "$opt" in
    (-h)
      no_server=1
      ;;
  esac
done

if [ ${no_server:-0} = 0 ]; then
  fifo=/tmp/scr-test-fifo
  if [ ! -e $fifo ]; then
    mkfifo $fifo
  fi
  npm start -- -p $SCR_PORT -n $fifo &
  pid=$!
  trap "trap - INT QUIT EXIT TERM;rm -f $fifo;kill $pid" INT QUIT EXIT TERM
  # once this read is done, we know the server is up and listening
  read port<$fifo
  rm $fifo
fi

./client -p $SCR_PORT -t "$@"
