" vim:comments+=b\:"
set nocompatible expandtab tabstop=2

if has("autocmd")
  let g:scrPrevLine=-1
  fu ScrSelectPassword()
    let l:lnum=line('.')
    if l:lnum==g:scrPrevLine
      " only invoke the logic below if cursor has moved to a new line
      return
    endif
    let g:scrPrevLine=l:lnum
    let l:line=getline('.')
    let [l:pw,l:start,l:end]=matchstrpos(l:line,':[^:]*$')
    let l:pw=strpart(l:pw,1)
    "call setpos("'<",[0,l:lnum,l:start+2,0])
    "call setpos("'>",[0,l:lnum,l:end,0])
    "normal! gv
    if len(l:pw)>0
      " use named register "p for the password
      let @p=l:pw
      echo "press ctrl-c to copy the password on line" l:lnum
    else
      let @p=""
      echo
    endif
  endf

  " when editing the passwords file, remap * to copy the current word to OS
  " clipboard use the expand() function to highlight the current word (cword)
  " nmap: "n" means we are mapping a key in vim's normal mode
  "autocmd BufReadPre,FileReadPre *.asc nmap <buffer> * :let @/=expand("<cword>")<cr>:let @"=@/<cr>:call ScrSetClipboard()<cr>
  autocmd BufReadPre,FileReadPre passwords.asc nnoremap <c-c> :call ScrSetClipboard(@p)<cr>
  autocmd CursorMoved passwords.asc :call ScrSelectPassword()
  autocmd FileType make setlocal noexpandtab
endif

colorscheme murphy
" map F8 to go to the next colorscheme
nnoremap <F8> :call ScrNextColorScheme(1)<CR>
" mac terminal shift-F8 to go backward in the colorscheme list
nnoremap <ESC>[29~ :call ScrNextColorScheme(-1)<CR>

syntax enable
set cursorline noswapfile number hlsearch incsearch sw=2 ignorecase wrap
set ruler ai nocindent indentexpr= showmatch modeline modelines=5 nobackup nowritebackup textwidth=0
set formatoptions=croql nojoinspaces scrolloff=0 laststatus=2
set wildmenu wildignore=*.o,*.class,*.jar,*.png,*.pdf,$PWD/**node_modules/**,build/**,.git/**,.svn/**,dist/**,tmp/** path=.,,** wildignorecase
set iskeyword+=-
if v:version>=704
  " make editing .ts (typescript) files easier
  set re=0
endif
filetype indent off
" vnoremap: 'v' visual mode, 'nore' no recurse, 'map' map
" here we remap control-c to yank the current visual selection into register p,
" and then copy it into the OS clipboard
vnoremap <c-c> "py:call ScrSetClipboard(@p)<cr>
nnoremap <c-v> :call ScrPasteClipboard()<cr>
