set nocompatible

if has("autocmd")
  let g:scrPrevLine=-1
  fu ScrSelectPassword()
    let l:lnum=line('.')
    if l:lnum==g:scrPrevLine
      " only invoke the logic below if cursor has moved to a new line
      return
    endif
    let g:scrPrevLine=l:lnum
    let l:line=getline('.')
    let [l:pw,l:start,l:end]=matchstrpos(l:line,':[^:]*$')
    let l:pw=strpart(l:pw,1)
    "call setpos("'<",[0,l:lnum,l:start+2,0])
    "call setpos("'>",[0,l:lnum,l:end,0])
    "normal! gv
    let @"=l:pw
    if len(l:pw)>0
      echo "press ctrl-c to copy the password on line" l:lnum
    else
      echo
    endif
  endf

  " when editing the passwords file, remap * to copy the current word to OS clipboard
  " use the expand() function to highlight the current word (cword)
  " nmap: "n" means we are mapping a key in vim's normal mode
  "autocmd BufReadPre,FileReadPre *.gpg nmap <buffer> * :let @/=expand("<cword>")<cr>:let @"=@/<cr>:call ScrSetClipboard()<cr>
  autocmd BufReadPre,FileReadPre passwords.gpg nnoremap <c-c> :call ScrSetClipboard()<cr>
  autocmd CursorMoved passwords.gpg :call ScrSelectPassword()

  " Transparent editing of gpg encrypted files.
  " By Wouter Hanegraaff
  augroup encrypted
    au!

    " First make sure nothing is written to ~/.viminfo while editing
    " an encrypted file.
    autocmd BufReadPre,FileReadPre *.gpg set viminfo=
    " We don't want a swap file, as it writes unencrypted data to disk
    autocmd BufReadPre,FileReadPre *.gpg set noswapfile

    " Switch to binary mode to read the encrypted file
    autocmd BufReadPre,FileReadPre *.gpg set bin
    autocmd BufReadPre,FileReadPre *.gpg let ch_save = &ch|set ch=2
    " (If you use tcsh, you may need to alter this line.)
    autocmd BufReadPost,FileReadPost *.gpg '[,']!gpg -d 2>/dev/null

    " Switch to normal mode for editing
    autocmd BufReadPost,FileReadPost *.gpg set nobin
    autocmd BufReadPost,FileReadPost *.gpg let &ch = ch_save|unlet ch_save
    autocmd BufReadPost,FileReadPost *.gpg execute ":doautocmd BufReadPost " . expand("%:r")

    " Convert all text to encrypted text before writing
    " (If you use tcsh, you may need to alter this line.)
    autocmd BufWritePre,FileWritePre *.gpg '[,']!gpg --default-recipient-self -ae 2>/dev/null
    " Undo the encryption so we are back in the normal text, directly
    " after the file has been written.
    autocmd BufWritePost,FileWritePost *.gpg u
  augroup END
endif

colorscheme elflord
syntax enable
set cursorline noswapfile number hlsearch incsearch sw=2 ignorecase wrap
set ruler ai nocindent indentexpr= showmatch modeline modelines=5 nobackup nowritebackup textwidth=0
set expandtab formatoptions=croql nojoinspaces scrolloff=0 laststatus=2
set wildmenu wildignore=*.o,*.class,*.jar,*.png,*.pdf,$PWD/**node_modules/**,build/**,.git/**,.svn/**,dist/**,tmp/** path=.,,**
set runtimepath+=$SCR_VIMRUNTIME iskeyword+=-
if v:version>=704
  " make editing .ts (typescript) files easier
  set re=0
endif
filetype indent off
" vnoremap: 'v' visual mode, 'nore' no recurse, 'map' map
" here we remap control-c to copy the current visual selection to the OS clipboard
vnoremap <c-c> y:call ScrSetClipboard()<cr>
nnoremap <c-v> :call ScrPasteClipboard()<cr>
